# Generated by Django 4.2 on 2023-04-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='food',
        ),
        migrations.DeleteModel(
            name='CantidadesReseta',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
        migrations.DeleteModel(
            name='Reseta',
        ),
    ]
