import Head from 'next/head'
import Layer from '@/components/Layer'
// const ""({ subsets: ['latin'] })

import fetcher from '@/scripts/fetcher';
import sortTable from '@/scripts/sortTable';
import { useEffect, useState } from 'react';
import DataTableDispaly from '@/components/DataTableDispaly';




export default function Home() {



  const [data, setData] = useState()


  useEffect(() => {
    fetcher(process.env.NEXT_PUBLIC_API_URL + "api/alimentos/foods/").then(res => setData(res))
  }, [])



  const trag_type = (type) => {



    return <td className='flex'>
      <div
        className={`tag 
      ${type == "CARBOHIDRATO" && "tag-red"}
      ${type == "PROTEINA" && "tag-green"}
      ${type == "GRASA" && "tag-blue"} `}>
      
      {type}
      </div>
    </td>

  }
  return (
    <Layer>
      <Head>
        <title>Gnutry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>

        list todo

        <ul>
          <li>display y seleccion de vistas por valores, mayor costo, mayor cantidad de macro etc</li>
        </ul>


        <div className={"center"}>


          <h1 className='text-4xl'>Listado de alimentos</h1>

          {data != null &&
            // <DataTableDispaly data={data} />
            <table className='table'>
              <thead>
                <tr>
                  <th onClick={e => sortTable(e)}>Nombre</th>
                  <th  onClick={e => sortTable(e)} >Tipo</th>
                  <th  onClick={e => sortTable(e)} >Kcal / 100gr</th>
                  <th  onClick={e => sortTable(e)} >proteina / 100gr</th>
                </tr>
              </thead>

              <tbody>
                {data != null && data != undefined &&
                  data.map((e, i) => (
                    <tr key={i} >
                      <td> {e.name} </td>

                      {trag_type(e.type)}



                      <td> {e.calorias} </td>
                      <td> {e.proteina} </td>
                    </tr>
                  ))
                }
              </tbody>

            </table>
          }





        </div>


      </main>
    </Layer>
  )
}
