# Generated by Django 4.2 on 2023-04-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('CARBOHIDRATO', 'carbohidrato'), ('GRASA', 'grasa'), ('PROTEINA', 'proteina')], max_length=200)),
                ('calorias', models.IntegerField(help_text='por cada 100g')),
                ('proteina', models.IntegerField(help_text='por cada 100g')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.food')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.origen')),
            ],
        ),
    ]
